spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/vdb
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  data:
    web:
      pageable:
        one-indexed-parameters: true


logging:
  level:
    sql: debug

