spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "*"

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/vdb
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  data:
    web:
      pageable:
        one-indexed-parameters: true

application:
  api:
    nvd:
      api-key: ${NVD_API_KEY}

  security:
    jwt:
      secret-key: ${ACCESS_TOKEN_SECRET_KEY}
      expiration: ${ACCESS_TOKEN_EXPIRATION}
      refresh-token:
        secret-key: ${REFRESH_TOKEN_SECRET_KEY}
        expiration: ${REFRESH_TOKEN_EXPIRATION}

logging:
  level:
    sql: debug

